apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-service
  namespace: chat-app
spec:
  type: ClusterIP
  selector:
    app: chat-app-server
  ports:
    - port: 8080
      targetPort: 8080

