apiVersion: v1
kind: Service
metadata:
  name: mongodbcontainer
  namespace: production-namespace
spec:
  clusterIP: None 
  selector:
    app: mongo
  ports:
    - port: 27017
      name: mongocontainer
      targetPort: 27017
